# sample regex patterns
ignore:
  - "**/RcppExport*"  # ignore all RcppExport files
coverage:
  status:
    project:
      default:
        target: 90%
        paths:
          - "src"
          - "R"
