test_that("Poisson residual no error", {
  a <- c(1, 1, 2, 3, 4, 5, 6)
  b <- c(1, 2, 3, 4, 5, 6, 7)
  c <- c(0, 1, 0, 0, 0, 1, 0)
  d <- c(3, 4, 5, 6, 7, 8, 9)
  e <- c(0, 0, 0, 1, 1, 1, 1)
  df <- data.table("a" = a, "b" = b, "c" = c, "d" = d, "e" = e)
  keep_constant <- 0
  a_n <- -0.1

  control <- list("ncores" = 1, "lr" = 0.95, "maxiter" = -1, "halfmax" = 1, "epsilon" = 1e-9, "deriv_epsilon" = 1e-9, "step_max" = 1.0, "change_all" = TRUE, "thres_step_max" = 1.0, "verbose" = 0)
  formula <- Poisson(a, c) ~ loglinear(d, 0)
  model <- get_form(formula, df)$model
  poisres <- PoisRun(model, df, control = control, a_n = a_n)
  #
  expect_no_error(e <- Residual(poisres, df, pearson = FALSE, deviance = FALSE))
  expect_equal(e$Risk, exp(-0.1 * df$d), tolerance = 1e-4)
  expect_no_error(e <- Residual(poisres, df, pearson = TRUE, deviance = FALSE))
  expect_equal(e$Pearson_Residual, (df$c - df$a * e$Risk)^2 / (df$a * e$Risk), tolerance = 1e-4)
  expect_no_error(e <- Residual(poisres, df, pearson = FALSE, deviance = TRUE))
  expect_equal(e$Deviance_Residual, 2 * (df$c * log((df$c + 1e-6) / (df$a * e$Risk)) - (df$c - df$a * e$Risk)), tolerance = 1e-4)
  expect_no_error(e <- Residual(poisres, df, pearson = TRUE, deviance = TRUE))
  expect_equal(e$Pearson_Residual, (df$c - df$a * e$Risk)^2 / (df$a * e$Risk), tolerance = 1e-4)
  expect_equal(e$Deviance_Residual, 2 * (df$c * log((df$c + 1e-6) / (df$a * e$Risk)) - (df$c - df$a * e$Risk)), tolerance = 1e-4)
  expect_equal(e$Raw_Residual, (df$c - df$a * e$Risk), tolerance = 1e-4)
  #
  expect_no_error(e <- Residual(model, df, pearson = FALSE, deviance = FALSE, a_n = a_n))
  expect_equal(e$Risk, exp(-0.1 * df$d), tolerance = 1e-4)
  expect_no_error(e <- Residual(model, df, pearson = TRUE, deviance = FALSE, a_n = a_n))
  expect_equal(e$Pearson_Residual, (df$c - df$a * e$Risk)^2 / (df$a * e$Risk), tolerance = 1e-4)
  expect_no_error(e <- Residual(model, df, pearson = FALSE, deviance = TRUE, a_n = a_n))
  expect_equal(e$Deviance_Residual, 2 * (df$c * log((df$c + 1e-6) / (df$a * e$Risk)) - (df$c - df$a * e$Risk)), tolerance = 1e-4)
  expect_no_error(e <- Residual(model, df, pearson = TRUE, deviance = TRUE, a_n = a_n))
  expect_equal(e$Pearson_Residual, (df$c - df$a * e$Risk)^2 / (df$a * e$Risk), tolerance = 1e-4)
  expect_equal(e$Deviance_Residual, 2 * (df$c * log((df$c + 1e-6) / (df$a * e$Risk)) - (df$c - df$a * e$Risk)), tolerance = 1e-4)
  expect_equal(e$Raw_Residual, (df$c - df$a * e$Risk), tolerance = 1e-4)
  #
  c <- c(0, 0, 0, 0, 0, 1, 0)
  e <- c(0, 0, 0, 1, 1, 1, 1)
  df <- data.table("a" = a, "b" = b, "c" = c, "d" = d, "e" = e)
  formula <- Poisson_Strata(a, c, e) ~ loglinear(d, 0)
  model <- get_form(formula, df)$model
  poisres_s <- PoisRun(model, df, control = control, a_n = a_n)
  expect_no_error(e <- Residual(poisres_s, df, pearson = TRUE, deviance = FALSE))
  expect_equal(e$Risk, c(0.0, 0.0, 0.0, 0.06597214, 0.05969406, 0.05401342, 0.04887337), tolerance = 1e-4)
  expect_no_error(e <- Residual(model, df, pearson = TRUE, deviance = FALSE, a_n = a_n))
  expect_equal(e$Risk, c(0.0, 0.0, 0.0, 0.06597214, 0.05969406, 0.05401342, 0.04887337), tolerance = 1e-4)
  a <- c(0, 1, 2, 3, 4, 5, 6)
  b <- c(1, 2, 3, 4, 5, 6, 7)
  c <- c(0, 0, 0, 0, 0, 0, 0)
  d <- c(3, 4, 5, 6, 7, 8, 9)
  e <- c(0, 0, 0, 1, 1, 1, 1)
  df <- data.table("a" = a, "b" = b, "c" = c, "d" = d, "e" = e)
  expect_error(e <- Residual(poisres_s, df, pearson = FALSE, deviance = TRUE))
  expect_error(Residual(model, df, pearson = FALSE, deviance = TRUE))
  a <- c(0, 0, 0, 0, 0, 0, 0)
  b <- c(1, 2, 3, 4, 5, 6, 7)
  c <- c(0, 1, 0, 0, 0, 1, 0)
  d <- c(3, 4, 5, 6, 7, 8, 9)
  e <- c(0, 0, 0, 1, 1, 1, 1)
  df <- data.table("a" = a, "b" = b, "c" = c, "d" = d, "e" = e)
  expect_error(e <- Residual(poisres_s, df, pearson = FALSE, deviance = TRUE))
  expect_error(Residual(model, df, pearson = FALSE, deviance = TRUE))
})

test_that("Logistic residual no error", {
  a <- c(1, 1, 2, 3, 4, 5, 6)
  b <- c(1, 2, 3, 4, 5, 6, 7)
  c <- c(0, 1, 0, 0, 0, 1, 0)
  d <- c(3, 4, 5, 6, 7, 8, 9)
  e <- c(0, 0, 0, 1, 1, 1, 1)
  df <- data.table("a" = a, "b" = b, "c" = c, "d" = d, "e" = e)
  keep_constant <- 0
  a_n <- -0.35

  control <- list("ncores" = 1, "lr" = 0.95, "maxiter" = -1, "halfmax" = 1, "epsilon" = 1e-9, "deriv_epsilon" = 1e-9, "step_max" = 1.0, "change_all" = TRUE, "thres_step_max" = 1.0, "verbose" = 0)
  formula <- Logit(a, c) ~ loglinear(d, 0)
  model <- get_form(formula, df)$model
  logitres <- LogisticRun(model, df, control = control, a_n = a_n)
  #
  expect_no_error(e <- Residual(logitres, df, pearson = FALSE, deviance = FALSE))
  expect_equal(e$Probability, c(0.25922510, 0.19781611, 0.14804720, 0.10909682, 0.07943855, 0.05732418, 0.04109128), tolerance = 1e-4)
  expect_no_error(e <- Residual(logitres, df, pearson = TRUE, deviance = FALSE))
  expect_equal(e$Pearson_Residual, (df$c - df$a * e$Probability) / sqrt(df$a * e$Probability * (1 - e$Probability)), tolerance = 1e-4)
  expect_no_error(e <- Residual(logitres, df, pearson = FALSE, deviance = TRUE))
  expect_equal(e$Deviance_Residual, abs(df$c - df$a * e$Probability) / (df$c - df$a * e$Probability) * sqrt(2 * (df$c * log((df$c + 1e-6) / (df$a * e$Probability)) + (df$a - df$c) * log((df$a - df$c + 1e-6) / (df$a - df$a * e$Probability)))), tolerance = 1e-4)
  expect_no_error(e <- Residual(logitres, df, pearson = TRUE, deviance = TRUE))
  expect_equal(e$Pearson_Residual, (df$c - df$a * e$Probability) / sqrt(df$a * e$Probability * (1 - e$Probability)), tolerance = 1e-4)
  expect_equal(e$Deviance_Residual, abs(df$c - df$a * e$Probability) / (df$c - df$a * e$Probability) * sqrt(2 * (df$c * log((df$c + 1e-6) / (df$a * e$Probability)) + (df$a - df$c) * log((df$a - df$c + 1e-6) / (df$a - df$a * e$Probability)))), tolerance = 1e-4)
  expect_equal(e$Raw_Residual, (df$c - df$a * e$Probability), tolerance = 1e-4)
  #
  expect_no_error(e <- Residual(model, df, pearson = FALSE, deviance = FALSE, a_n = a_n))
  expect_equal(e$Probability, c(0.25922510, 0.19781611, 0.14804720, 0.10909682, 0.07943855, 0.05732418, 0.04109128), tolerance = 1e-4)
  expect_no_error(e <- Residual(model, df, pearson = TRUE, deviance = FALSE, a_n = a_n))
  expect_equal(e$Pearson_Residual, (df$c - df$a * e$Probability) / sqrt(df$a * e$Probability * (1 - e$Probability)), tolerance = 1e-4)
  expect_no_error(e <- Residual(model, df, pearson = FALSE, deviance = TRUE, a_n = a_n))
  expect_equal(e$Deviance_Residual, abs(df$c - df$a * e$Probability) / (df$c - df$a * e$Probability) * sqrt(2 * (df$c * log((df$c + 1e-6) / (df$a * e$Probability)) + (df$a - df$c) * log((df$a - df$c + 1e-6) / (df$a - df$a * e$Probability)))), tolerance = 1e-4)
  expect_no_error(e <- Residual(model, df, pearson = TRUE, deviance = TRUE, a_n = a_n))
  expect_equal(e$Pearson_Residual, (df$c - df$a * e$Probability) / sqrt(df$a * e$Probability * (1 - e$Probability)), tolerance = 1e-4)
  expect_equal(e$Deviance_Residual, abs(df$c - df$a * e$Probability) / (df$c - df$a * e$Probability) * sqrt(2 * (df$c * log((df$c + 1e-6) / (df$a * e$Probability)) + (df$a - df$c) * log((df$a - df$c + 1e-6) / (df$a - df$a * e$Probability)))), tolerance = 1e-4)
  expect_equal(e$Raw_Residual, (df$c - df$a * e$Probability), tolerance = 1e-4)
  #
  a <- c(0, 1, 2, 3, 4, 5, 6)
  b <- c(1, 2, 3, 4, 5, 6, 7)
  c <- c(0, 0, 0, 0, 0, 0, 0)
  d <- c(3, 4, 5, 6, 7, 8, 9)
  e <- c(0, 0, 0, 1, 1, 1, 1)
  df <- data.table("a" = a, "b" = b, "c" = c, "d" = d, "e" = e)
  expect_error(e <- Residual(logitres, df, pearson = FALSE, deviance = TRUE))
  expect_error(Residual(model, df, pearson = FALSE, deviance = TRUE))
  a <- c(0, 0, 0, 0, 0, 0, 0)
  b <- c(1, 2, 3, 4, 5, 6, 7)
  c <- c(0, 1, 0, 0, 0, 1, 0)
  d <- c(3, 4, 5, 6, 7, 8, 9)
  e <- c(0, 0, 0, 1, 1, 1, 1)
  df <- data.table("a" = a, "b" = b, "c" = c, "d" = d, "e" = e)
  expect_error(e <- Residual(logitres, df, pearson = FALSE, deviance = TRUE))
  expect_error(Residual(model, df, pearson = FALSE, deviance = TRUE))
})

test_that("Residual warnings", {
  a <- c(1, 1, 2, 3, 4, 5, 6)
  b <- c(1, 2, 3, 4, 5, 6, 7)
  c <- c(0, 1, 0, 0, 0, 1, 0)
  d <- c(3, 4, 5, 6, 7, 8, 9)
  e <- c(0, 0, 0, 1, 1, 1, 1)
  df <- data.table("a" = a, "b" = b, "c" = c, "d" = d, "e" = e)
  keep_constant <- 0
  a_n <- -0.35

  control <- list("ncores" = 1, "lr" = 0.95, "maxiter" = -1, "halfmax" = 1, "epsilon" = 1e-9, "deriv_epsilon" = 1e-9, "step_max" = 1.0, "change_all" = TRUE, "thres_step_max" = 1.0, "verbose" = 0)
  formula <- Cox(a, c) ~ loglinear(d, 0)
  model <- get_form(formula, df)$model
  coxres <- CoxRun(model, df, control = control, a_n = a_n)
  expect_warning(Residual(model))
  expect_warning(Residual(coxres))
})
