# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Utility function to take the norm of a vector
#' \code{vec_norm} Called within the code, takes a vector and length and finds the norm
#' @param     x    std::vector to take norm of, assumed doubles
#' @param     totalnum    vector length
#'
#' @return double of the norm
vec_norm <- function(x, totalnum) {
    .Call(`_Colossus_vec_norm`, x, totalnum)
}

#' Utility function to remove rows
#' \code{removeRow} Called within the code, removes and resizes the matrix
#' @param     matrix    Eigen matrix to change
#' @param     rowToRemove    row index to remove
#'
#' @return eigen matrix with the row removed
removeRow <- function(matrix, rowToRemove) {
    invisible(.Call(`_Colossus_removeRow`, matrix, rowToRemove))
}

#' Utility function to remove rows
#' \code{removeColumn} Called within the code, removes and resizes the matrix
#' @param     matrix    Eigen matrix to change
#' @param     colToRemove    column index to remove
#'
#' @return eigen matrix with the column removed
removeColumn <- function(matrix, colToRemove) {
    invisible(.Call(`_Colossus_removeColumn`, matrix, colToRemove))
}

#' Utility function to calculate the term and subterm values
#' \code{Make_Subterms} Called to update term matrices, Uses lists of term numbers and types to apply formulas
#' @param     totalnum    Total number of terms
#' @param     Term_n    Term numbers
#' @param     tform    subterm types
#' @param     dfc    covariate column numbers
#' @param     fir    first term number
#' @param     T0    Term by subterm matrix
#' @param     Td0    Term by subterm derivative matrix
#' @param     Tdd0    Term by subterm second derivative matrix
#' @param     Dose    Dose term matrix
#' @param     nonDose    nonDose term matrix
#' @param     TTerm    Total term matrix
#' @param     nonDose_LIN    Linear term matrix
#' @param     nonDose_PLIN    Product linear term matrix
#' @param     nonDose_LOGLIN    Loglinear term matrix
#' @param     beta_0    parameter list
#' @param     df0    covariate matrix
#' @param     dint    value used for threshold derivative finite step
#' @param     dslp    value used for slope derivative finite step
#' @param     nthreads    number of threads to use
#' @param     debugging    debugging boolean
#'
#' @return Updates matrices in place: Sub-term matrices, Term matrices
Make_Subterms <- function(totalnum, Term_n, tform, dfc, fir, T0, Td0, Tdd0, Dose, nonDose, TTerm, nonDose_LIN, nonDose_PLIN, nonDose_LOGLIN, beta_0, df0, dint, dslp, nthreads, debugging) {
    invisible(.Call(`_Colossus_Make_Subterms`, totalnum, Term_n, tform, dfc, fir, T0, Td0, Tdd0, Dose, nonDose, TTerm, nonDose_LIN, nonDose_PLIN, nonDose_LOGLIN, beta_0, df0, dint, dslp, nthreads, debugging))
}

#' Utility function to calculate the term and subterm values with the basic model
#' \code{Make_Subterms_Basic} Called to update term matrices, Uses lists of term numbers and types to apply formulas
#' @param     totalnum    Total number of terms
#' @param     dfc    covariate column numbers
#' @param     T0    subterm values
#' @param     beta_0    parameter list
#' @param     df0    covariate matrix
#' @param     nthreads    number of threads to use
#' @param     debugging    debugging boolean
#'
#' @return Updates matrices in place: Sub-term matrices, Term matrices
Make_Subterms_Basic <- function(totalnum, dfc, T0, beta_0, df0, nthreads, debugging) {
    invisible(.Call(`_Colossus_Make_Subterms_Basic`, totalnum, dfc, T0, beta_0, df0, nthreads, debugging))
}

#' Utility function to calculate the risk and risk ratios
#' \code{Make_Risks} Called to update risk matrices, Splits into cases based on model form, Uses lists of term numbers and types to apply different derivative formulas    
#' @param     modelform    Model string
#' @param     tform    subterm types
#' @param     Term_n    term numbers
#' @param     totalnum    total number of terms
#' @param     fir    first term number
#' @param     T0    Term by subterm matrix
#' @param     Td0    Term by subterm derivative matrix
#' @param     Tdd0    Term by subterm second derivative matrix
#' @param     Te    Temporary term storage matrix
#' @param     R    Risk matrix
#' @param     Rd    Risk first derivative matrix
#' @param     Rdd    Risk second derivative matrix
#' @param     Dose    Dose term matrix
#' @param     nonDose    nonDose term matrix
#' @param     TTerm    Total term matrix
#' @param     nonDose_LIN    Linear term matrix
#' @param     nonDose_PLIN    Product linear term matrix
#' @param     nonDose_LOGLIN    Loglinear term matrix
#' @param     RdR    Risk to first derivative ratio matrix
#' @param     RddR    Risk to second derivative ratio matrix
#' @param     nthreads    number of threads to use
#' @param     debugging    debugging boolean
#'
#' @return Updates matrices in place: Risk, Risk ratios
Make_Risks <- function(modelform, tform, Term_n, totalnum, fir, T0, Td0, Tdd0, Te, R, Rd, Rdd, Dose, nonDose, TTerm, nonDose_LIN, nonDose_PLIN, nonDose_LOGLIN, RdR, RddR, nthreads, debugging) {
    invisible(.Call(`_Colossus_Make_Risks`, modelform, tform, Term_n, totalnum, fir, T0, Td0, Tdd0, Te, R, Rd, Rdd, Dose, nonDose, TTerm, nonDose_LIN, nonDose_PLIN, nonDose_LOGLIN, RdR, RddR, nthreads, debugging))
}

#' Utility function to calculate the risk and risk ratios for the basic model
#' \code{Make_Risks_Basic} Called to update risk matrices, Splits into cases based on model form, Uses lists of term numbers and types to apply different derivative formulas    
#' @param     totalnum    total number of terms
#' @param     T0    Term by subterm matrix
#' @param     R    Risk matrix
#' @param     Rd    Risk first derivative matrix
#' @param     Rdd    Risk second derivative matrix
#' @param     RdR    Risk to first derivative ratio matrix
#' @param     RddR    Risk to second derivative ratio matrix
#' @param     nthreads    number of threads to use
#' @param     debugging    debugging boolean
#' @param     df0    covariate matrix
#' @param     dfc    covariate column numbers
#'
#' @return Updates matrices in place: Risk, Risk ratios
Make_Risks_Basic <- function(totalnum, T0, R, Rd, Rdd, RdR, RddR, nthreads, debugging, df0, dfc) {
    invisible(.Call(`_Colossus_Make_Risks_Basic`, totalnum, T0, R, Rd, Rdd, RdR, RddR, nthreads, debugging, df0, dfc))
}

#' Utility function to define risk groups
#' \code{Make_Groups} Called to update lists of risk groups, Uses list of event times and row time/event information, Matrices store starting/stopping row indices for each group    
#' @param     ntime    number of event times
#' @param     df_m    event/time matrix
#' @param     RiskFail    Matrix of event rows for each event time
#' @param     RiskGroup    vectors of strings with rows at risk for each event time
#' @param     tu    Event time vector
#' @param     nthreads    number of threads
#' @param     debugging    debugging boolean
#'
#' @return Updates matrices in place: Matrix of event rows for each event time, vectors of strings with rows at risk for each event time
Make_Groups <- function(ntime, df_m, RiskFail, RiskGroup, tu, nthreads, debugging) {
    invisible(.Call(`_Colossus_Make_Groups`, ntime, df_m, RiskFail, RiskGroup, tu, nthreads, debugging))
}

#' Utility function to define risk groups with STRATA
#' \code{Make_Groups_STRATA} Called to update lists of risk groups, Uses list of event times and row time/event information, Matrices store starting/stopping row indices for each group    
#' @param     ntime    number of event times
#' @param     df_m    event/time matrix
#' @param     RiskFail    Matrix of event rows for each event time
#' @param     RiskGroup    vectors of strings with rows at risk for each event time
#' @param     tu    Event time vector
#' @param     nthreads    number of threads
#' @param     debugging    debugging boolean
#' @param     STRATA_vals vector of strata identifier values
#'
#' @return Updates matrices in place: Matrix of event rows for each event time, vectors of strings with rows at risk for each event time
Make_Groups_STRATA <- function(ntime, df_m, RiskFail, RiskGroup, tu, nthreads, debugging, STRATA_vals) {
    invisible(.Call(`_Colossus_Make_Groups_STRATA`, ntime, df_m, RiskFail, RiskGroup, tu, nthreads, debugging, STRATA_vals))
}

#' Utility function to calculate repeated values used in Cox Log-Likelihood calculation
#' \code{Calculate_Sides} Called to update repeated sum calculations, Uses list of event rows and risk matrices, Performs calculation of sums of risk in each group
#' @param     RiskFail    Matrix of event rows for each event time
#' @param     RiskGroup    vectors of strings with rows at risk for each event time
#' @param     totalnum    total number of parameters
#' @param     ntime    number of event times
#' @param     R    Risk matrix
#' @param     Rd    Risk derivative matrix
#' @param     Rdd    Risk second derivative matrix
#' @param     Rls1    First Risk sum storage
#' @param     Rls2    First Risk sum derivative storage
#' @param     Rls3    First Risk sum second derivative storage
#' @param     Lls1    Second Risk sum storage
#' @param     Lls2    Second Risk sum derivative storage
#' @param     Lls3    Second Risk sum second derivative storage
#' @param     nthreads    number of threads
#' @param     debugging    debugging boolean
#'
#' @return Updates matrices in place: risk storage matrices
Calculate_Sides <- function(RiskFail, RiskGroup, totalnum, ntime, R, Rd, Rdd, Rls1, Rls2, Rls3, Lls1, Lls2, Lls3, nthreads, debugging) {
    invisible(.Call(`_Colossus_Calculate_Sides`, RiskFail, RiskGroup, totalnum, ntime, R, Rd, Rdd, Rls1, Rls2, Rls3, Lls1, Lls2, Lls3, nthreads, debugging))
}

#' Utility function to calculate repeated values used in Cox Log-Likelihood calculation with STRATA
#' \code{Calculate_Sides_STRATA} Called to update repeated sum calculations, Uses list of event rows and risk matrices, Performs calculation of sums of risk in each group
#' @param     RiskFail    Matrix of event rows for each event time
#' @param     RiskGroup    vectors of strings with rows at risk for each event time
#' @param     totalnum    total number of parameters
#' @param     ntime    number of event times
#' @param     R    Risk matrix
#' @param     Rd    Risk derivative matrix
#' @param     Rdd    Risk second derivative matrix
#' @param     Rls1    First Risk sum storage
#' @param     Rls2    First Risk sum derivative storage
#' @param     Rls3    First Risk sum second derivative storage
#' @param     Lls1    Second Risk sum storage
#' @param     Lls2    Second Risk sum derivative storage
#' @param     Lls3    Second Risk sum second derivative storage
#' @param     nthreads    number of threads
#' @param     debugging    debugging boolean
#' @param     STRATA_vals vector of strata identifier values
#'
#' @return Updates matrices in place: risk storage matrices
Calculate_Sides_STRATA <- function(RiskFail, RiskGroup, totalnum, ntime, R, Rd, Rdd, Rls1, Rls2, Rls3, Lls1, Lls2, Lls3, nthreads, debugging, STRATA_vals) {
    invisible(.Call(`_Colossus_Calculate_Sides_STRATA`, RiskFail, RiskGroup, totalnum, ntime, R, Rd, Rdd, Rls1, Rls2, Rls3, Lls1, Lls2, Lls3, nthreads, debugging, STRATA_vals))
}

#' Utility function to calculate Cox Log-Likelihood and derivatives
#' \code{Calc_LogLik} Called to update log-likelihoods, Uses list of event rows, risk matrices, and repeated sums, Sums the log-likelihood contribution from each event time
#' @param     nthreads    number of threads
#' @param     RiskFail    Matrix of event rows for each event time
#' @param     RiskGroup    vectors of strings with rows at risk for each event time
#' @param     totalnum    total number of parameters
#' @param     ntime    number of event times
#' @param     R    Risk matrix
#' @param     Rd    Risk derivative matrix
#' @param     Rdd    Risk second derivative matrix
#' @param     RdR    Risk to first derivative ratio matrix
#' @param     RddR    Risk to second derivative ratio matrix
#' @param     Rls1    First Risk sum storage
#' @param     Rls2    First Risk sum derivative storage
#' @param     Rls3    First Risk sum second derivative storage
#' @param     Lls1    Second Risk sum storage
#' @param     Lls2    Second Risk sum derivative storage
#' @param     Lls3    Second Risk sum second derivative storage
#' @param     Ll    Log-likelihood vector
#' @param     Lld    Log-likelihood first derivative vector
#' @param     Lldd    Log-likelihood second derivative matrix
#' @param     debugging    debugging boolean
#' @param     ties_method    Ties method
#'
#' @return Updates matrices in place: Log-likelihood vectors/matrix
Calc_LogLik <- function(nthreads, RiskFail, RiskGroup, totalnum, ntime, R, Rd, Rdd, RdR, RddR, Rls1, Rls2, Rls3, Lls1, Lls2, Lls3, Ll, Lld, Lldd, debugging, ties_method) {
    invisible(.Call(`_Colossus_Calc_LogLik`, nthreads, RiskFail, RiskGroup, totalnum, ntime, R, Rd, Rdd, RdR, RddR, Rls1, Rls2, Rls3, Lls1, Lls2, Lls3, Ll, Lld, Lldd, debugging, ties_method))
}

#' Utility function to calculate Cox Log-Likelihood and derivatives with STRATA
#' \code{Calc_LogLik_STRATA} Called to update log-likelihoods, Uses list of event rows, risk matrices, and repeated sums, Sums the log-likelihood contribution from each event time
#' @param     nthreads    number of threads
#' @param     RiskFail    Matrix of event rows for each event time
#' @param     RiskGroup    vectors of strings with rows at risk for each event time
#' @param     totalnum    total number of parameters
#' @param     ntime    number of event times
#' @param     R    Risk matrix
#' @param     Rd    Risk derivative matrix
#' @param     Rdd    Risk second derivative matrix
#' @param     RdR    Risk to first derivative ratio matrix
#' @param     RddR    Risk to second derivative ratio matrix
#' @param     Rls1    First Risk sum storage
#' @param     Rls2    First Risk sum derivative storage
#' @param     Rls3    First Risk sum second derivative storage
#' @param     Lls1    Second Risk sum storage
#' @param     Lls2    Second Risk sum derivative storage
#' @param     Lls3    Second Risk sum second derivative storage
#' @param     Ll    Log-likelihood vector
#' @param     Lld    Log-likelihood first derivative vector
#' @param     Lldd    Log-likelihood second derivative matrix
#' @param     debugging    debugging boolean
#' @param     ties_method    Ties method
#' @param     STRATA_vals vector of strata identifier values
#'
#' @return Updates matrices in place: Log-likelihood vectors/matrix
Calc_LogLik_STRATA <- function(nthreads, RiskFail, RiskGroup, totalnum, ntime, R, Rd, Rdd, RdR, RddR, Rls1, Rls2, Rls3, Lls1, Lls2, Lls3, Ll, Lld, Lldd, debugging, ties_method, STRATA_vals) {
    invisible(.Call(`_Colossus_Calc_LogLik_STRATA`, nthreads, RiskFail, RiskGroup, totalnum, ntime, R, Rd, Rdd, RdR, RddR, Rls1, Rls2, Rls3, Lls1, Lls2, Lls3, Ll, Lld, Lldd, debugging, ties_method, STRATA_vals))
}

#' Utility function to calculate poisson log-likelihood and derivatives
#' \code{Poisson_LogLik} Called to update log-likelihoods, Uses list risk matrices and person-years, Sums the log-likelihood contribution from each row
#' @param     nthreads    number of threads
#' @param     totalnum    total number of parameters
#' @param     PyrC    person-year matrix
#' @param     R    Risk matrix
#' @param     Rd    Risk derivative matrix
#' @param     Rdd    Risk second derivative matrix
#' @param     RdR    Risk to first derivative ratio matrix
#' @param     RddR    Risk to second derivative ratio matrix
#' @param     Ll    Log-likelihood vector
#' @param     Lld    Log-likelihood first derivative vector
#' @param     Lldd    Log-likelihood second derivative matrix
#' @param     debugging    debugging boolean
#'
#' @return Updates matrices in place: Log-likelihood vectors/matrix
Poisson_LogLik <- function(nthreads, totalnum, PyrC, R, Rd, Rdd, RdR, RddR, Ll, Lld, Lldd, debugging) {
    invisible(.Call(`_Colossus_Poisson_LogLik`, nthreads, totalnum, PyrC, R, Rd, Rdd, RdR, RddR, Ll, Lld, Lldd, debugging))
}

#' Utility function to calculate the change to make each iteration
#' \code{Calc_Change} Called to update the parameter changes, Uses log-likelihoods and control parameters, Applys newton steps and change limitations    
#' @param     double_step controls the step calculation, 0 for independent changes, 1 for solving b=Ax with complete matrices
#' @param     nthreads    number of threads
#' @param     totalnum    total number of parameter
#' @param     fir    first term number
#' @param     der_iden    subterm number for derivative tests
#' @param     dbeta_cap    learning rate for newton step toward 0 log-likelihood
#' @param     dose_abs_max    Maximum allowed threshold parameter change
#' @param     lr    learning rate fo newton step toward 0 derivative
#' @param     abs_max    Maximum allowed parameter change
#' @param     Ll    Log-Likelihood
#' @param     Lld    Log-Likelihood first derivative
#' @param     Lldd    Log-Likelihood second derivative
#' @param     dbeta    parameter change vector
#' @param     change_all    boolean to change every parameter
#' @param     tform    subterm type
#' @param     dint    value used for threshold derivative calculation
#' @param     dslp    value used for slope derivative finite step
#' @param     KeepConstant    vector of parameters to keep constant
#' @param     debugging    debugging boolean
#'
#' @return Updates matrices in place: parameter change matrix
Calc_Change <- function(double_step, nthreads, totalnum, fir, der_iden, dbeta_cap, dose_abs_max, lr, abs_max, Ll, Lld, Lldd, dbeta, change_all, tform, dint, dslp, KeepConstant, debugging) {
    invisible(.Call(`_Colossus_Calc_Change`, double_step, nthreads, totalnum, fir, der_iden, dbeta_cap, dose_abs_max, lr, abs_max, Ll, Lld, Lldd, dbeta, change_all, tform, dint, dslp, KeepConstant, debugging))
}

#' Utility function to calculate the change to make each iteration, with basic model
#' \code{Calc_Change_Basic} Called to update the parameter changes, Uses log-likelihoods and control parameters, Applys newton steps and change limitations    
#' @param     double_step controls the step calculation, 0 for independent changes, 1 for solving b=Ax with complete matrices
#' @param     nthreads    number of threads
#' @param     totalnum    total number of parameter
#' @param     der_iden    subterm number for derivative tests
#' @param     dbeta_cap    learning rate for newton step toward 0 log-likelihood
#' @param     lr    learning rate fo newton step toward 0 derivative
#' @param     abs_max    Maximum allowed parameter change
#' @param     Ll    Log-Likelihood
#' @param     Lld    Log-Likelihood first derivative
#' @param     Lldd    Log-Likelihood second derivative
#' @param     dbeta    parameter change vector
#' @param     change_all    boolean to change every parameter
#' @param     KeepConstant    vector of parameters to keep constant
#' @param     debugging    debugging boolean
#'
#' @return Updates matrices in place: parameter change matrix
Calc_Change_Basic <- function(double_step, nthreads, totalnum, der_iden, dbeta_cap, lr, abs_max, Ll, Lld, Lldd, dbeta, change_all, KeepConstant, debugging) {
    invisible(.Call(`_Colossus_Calc_Change_Basic`, double_step, nthreads, totalnum, der_iden, dbeta_cap, lr, abs_max, Ll, Lld, Lldd, dbeta, change_all, KeepConstant, debugging))
}

#' Utility function to perform null model equivalent of Calculate_Sides
#' \code{Calculate_Null_Sides} Called to update repeated sum calculations, Uses list of event rows, Performs calculation of counts in each group
#' @param     RiskFail    Matrix of event rows for each event time
#' @param     RiskGroup    vectors of strings with rows at risk for each event time
#' @param     ntime    number of event times
#' @param     R    Risk matrix
#' @param     Rls1    First Risk sum storage
#' @param     Lls1    Second Risk sum storage
#' @param     nthreads    number of threads
#'
#' @return Updates matrices in place: risk storage matrices
Calculate_Null_Sides <- function(RiskFail, RiskGroup, ntime, R, Rls1, Lls1, nthreads) {
    invisible(.Call(`_Colossus_Calculate_Null_Sides`, RiskFail, RiskGroup, ntime, R, Rls1, Lls1, nthreads))
}

#' Utility function to perform null model equivalent of Calc_LogLik
#' \code{Calc_Null_LogLik} Called to update log-likelihoods, Uses list of event rows and repeated sums, Sums the log-likelihood contribution from each event time
#' @param     nthreads    number of threads
#' @param     RiskFail    Matrix of event rows for each event time
#' @param     RiskGroup    vectors of strings with rows at risk for each event time
#' @param     ntime    number of event times
#' @param     R    Risk matrix
#' @param     Rls1    First Risk sum storage
#' @param     Lls1    Second Risk sum storage
#' @param     Ll    Log-likelihood vector
#' @param     ties_method    Ties method
#'
#' @return Updates matrices in place: Log-likelihood vectors/matrix
Calc_Null_LogLik <- function(nthreads, RiskFail, RiskGroup, ntime, R, Rls1, Lls1, Ll, ties_method) {
    invisible(.Call(`_Colossus_Calc_Null_LogLik`, nthreads, RiskFail, RiskGroup, ntime, R, Rls1, Lls1, Ll, ties_method))
}

#' Primary Cox PH regression
#' \code{LogLik_Cox_PH} Performs the calls to calculation functions, Structures the Cox PH regression, With verbose option prints out time stamps and intermediate sums of terms and derivatives
#'
#' @param     Term_n    Term numbers
#' @param     tform    subterm types
#' @param     a_n    starting values
#' @param     x_all    covariate matrix
#' @param     dfc    covariate column numbers
#' @param     fir    first term number
#' @param     der_iden    subterm number for derivative tests
#' @param     modelform    model string
#' @param     lr    learning rate for newton step toward 0 derivative
#' @param     maxiter    maximum number of iterations
#' @param     halfmax    maximum number of half steps
#' @param     epsilon    minimum acceptable maximum parameter change
#' @param     dbeta_cap    learning rate for newton step toward 0 log-likelihood
#' @param     abs_max    Maximum allowed parameter change
#' @param     dose_abs_max    Maximum allowed threshold parameter change
#' @param     deriv_epsilon    threshold for near-zero derivative
#' @param     df_groups    matrix with time and event information
#' @param     tu    event times
#' @param     double_step controls the step calculation, 0 for independent changes, 1 for solving b=Ax with complete matrices
#' @param     change_all    boolean if every parameter is being updated
#' @param     verbose    verbosity boolean
#' @param     debugging    debugging boolean
#' @param     KeepConstant    vector identifying constant parameters
#' @param     term_tot    total number of terms
#' @param     ties_method    ties method
#'
#' @return List of results: Log-likelihood of optimum, first derivative of log-likelihood, second derivative matrix, parameter list, standard deviation estimate, AIC, model information
LogLik_Cox_PH <- function(Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, df_groups, tu, double_step, change_all, verbose, debugging, KeepConstant, term_tot, ties_method) {
    .Call(`_Colossus_LogLik_Cox_PH`, Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, df_groups, tu, double_step, change_all, verbose, debugging, KeepConstant, term_tot, ties_method)
}

#' Primary Cox PH regression with basic model
#' \code{LogLik_Cox_PH_basic} Performs the calls to calculation functions, Structures the Cox PH regression, With verbose option prints out time stamps and intermediate sums of terms and derivatives
#'
#' @param     a_n    starting values
#' @param     x_all    covariate matrix
#' @param     dfc    covariate column numbers
#' @param     der_iden    subterm number for derivative tests
#' @param     lr    learning rate for newton step toward 0 derivative
#' @param     maxiter    maximum number of iterations
#' @param     halfmax    maximum number of half steps
#' @param     epsilon    minimum acceptable maximum parameter change
#' @param     dbeta_cap    learning rate for newton step toward 0 log-likelihood
#' @param     abs_max    Maximum allowed parameter change
#' @param     dose_abs_max    Maximum allowed threshold parameter change
#' @param     deriv_epsilon    threshold for near-zero derivative
#' @param     df_groups    matrix with time and event information
#' @param     tu    event times
#' @param     double_step controls the step calculation, 0 for independent changes, 1 for solving b=Ax with complete matrices
#' @param     change_all    boolean if every parameter is being updated
#' @param     verbose    verbosity boolean
#' @param     debugging    debugging boolean
#' @param     KeepConstant    vector identifying constant parameters
#' @param     ties_method    ties method
#'
#' @return List of results: Log-likelihood of optimum, first derivative of log-likelihood, second derivative matrix, parameter list, standard deviation estimate, AIC, model information
LogLik_Cox_PH_basic <- function(a_n, x_all, dfc, der_iden, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, df_groups, tu, double_step, change_all, verbose, debugging, KeepConstant, ties_method) {
    .Call(`_Colossus_LogLik_Cox_PH_basic`, a_n, x_all, dfc, der_iden, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, df_groups, tu, double_step, change_all, verbose, debugging, KeepConstant, ties_method)
}

#' Primary Cox PH regression with STRATA effect
#' \code{LogLik_Cox_PH_STRATA} Performs the calls to calculation functions, Structures the Cox PH regression, With verbose option prints out time stamps and intermediate sums of terms and derivatives
#'
#' @param     Term_n    Term numbers
#' @param     tform    subterm types
#' @param     a_n    starting values
#' @param     x_all    covariate matrix
#' @param     dfc    covariate column numbers
#' @param     fir    first term number
#' @param     der_iden    subterm number for derivative tests
#' @param     modelform    model string
#' @param     lr    learning rate for newton step toward 0 derivative
#' @param     maxiter    maximum number of iterations
#' @param     halfmax    maximum number of half steps
#' @param     epsilon    minimum acceptable maximum parameter change
#' @param     dbeta_cap    learning rate for newton step toward 0 log-likelihood
#' @param     abs_max    Maximum allowed parameter change
#' @param     dose_abs_max    Maximum allowed threshold parameter change
#' @param     deriv_epsilon    threshold for near-zero derivative
#' @param     df_groups    matrix with time and event information
#' @param     tu    event times
#' @param     double_step controls the step calculation, 0 for independent changes, 1 for solving b=Ax with complete matrices
#' @param     change_all    boolean if every parameter is being updated
#' @param     verbose    verbosity boolean
#' @param     debugging    debugging boolean
#' @param     KeepConstant    vector identifying constant parameters
#' @param     term_tot    total number of terms
#' @param     ties_method    ties method
#' @param     STRATA_vals vector of strata identifier values
#'
#' @return List of results: Log-likelihood of optimum, first derivative of log-likelihood, second derivative matrix, parameter list, standard deviation estimate, AIC, model information
LogLik_Cox_PH_STRATA <- function(Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, df_groups, tu, double_step, change_all, verbose, debugging, KeepConstant, term_tot, ties_method, STRATA_vals) {
    .Call(`_Colossus_LogLik_Cox_PH_STRATA`, Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, df_groups, tu, double_step, change_all, verbose, debugging, KeepConstant, term_tot, ties_method, STRATA_vals)
}

#' Primary Cox PH baseline hazard function
#' \code{Cox_PH_PLOT_SURV} Performs the calls to calculation functions, Uses calculated risks and risk groups to approximate the baseline, With verbose option prints out time stamps and intermediate sums of terms and derivatives
#'
#' @param     Term_n    Term numbers
#' @param     tform    subterm types
#' @param     a_n    Optimal values
#' @param     a_er    Optimal value standard error
#' @param     x_all    covariate matrix
#' @param     dfc    covariate column numbers
#' @param     fir    first term number
#' @param     der_iden    subterm number for derivative tests
#' @param     modelform    model string
#' @param     abs_max    Maximum allowed parameter change
#' @param     dose_abs_max    Maximum allowed threshold parameter change
#' @param     df_groups    matrix with time and event information
#' @param     tu    event times
#' @param     verbose    verbosity boolean
#' @param     debugging    debugging boolean
#' @param     KeepConstant    vector identifying constant parameters
#' @param     term_tot    total number of terms
#'
#' @return List of results: baseline harzard, risk for each row
Cox_PH_PLOT_SURV <- function(Term_n, tform, a_n, a_er, x_all, dfc, fir, der_iden, modelform, abs_max, dose_abs_max, df_groups, tu, verbose, debugging, KeepConstant, term_tot) {
    .Call(`_Colossus_Cox_PH_PLOT_SURV`, Term_n, tform, a_n, a_er, x_all, dfc, fir, der_iden, modelform, abs_max, dose_abs_max, df_groups, tu, verbose, debugging, KeepConstant, term_tot)
}

#' Primary Cox PH risk plotting function
#' \code{Cox_PH_PLOT_RISK} Performs the calls to calculation functions, Uses formula and a generated list of covariate values to calculate risk over a grid, With verbose option prints out time stamps and intermediate sums of terms and derivatives
#'
#' @param     Term_n    Term numbers
#' @param     tform    subterm types
#' @param     a_n    starting values
#' @param     x_all    covariate matrix
#' @param     dfc    covariate column numbers
#' @param     fir    first term number
#' @param     der_iden    subterm number for derivative tests
#' @param     modelform    model string
#' @param     abs_max    Maximum allowed parameter change
#' @param     dose_abs_max    Maximum allowed threshold parameter change
#' @param     df_groups    matrix with time and event information
#' @param     tu    event times
#' @param     verbose    verbosity boolean
#' @param     debugging    debugging boolean
#' @param     KeepConstant    vector identifying constant parameters
#' @param     term_tot    total number of terms
#' @param     uniq_v    number of unqiue covariate values
#'
#' @return List of results: covariate values, risks for each row
Cox_PH_PLOT_RISK <- function(Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, abs_max, dose_abs_max, df_groups, tu, verbose, debugging, KeepConstant, term_tot, uniq_v) {
    .Call(`_Colossus_Cox_PH_PLOT_RISK`, Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, abs_max, dose_abs_max, df_groups, tu, verbose, debugging, KeepConstant, term_tot, uniq_v)
}

#' Primary Cox PH schoenfeld residual function
#' \code{Schoenfeld_Cox_PH} Performs the calls to calculation functions, Uses calculated risks and risk groups to calculate the residuals, With verbose option prints out time stamps and intermediate sums of terms and derivatives
#'
#' @param     Term_n    Term numbers
#' @param     tform    subterm types
#' @param     a_n    starting values
#' @param     x_all    covariate matrix
#' @param     dfc    covariate column numbers
#' @param     fir    first term number
#' @param     der_iden    subterm number for derivative tests
#' @param     modelform    model string
#' @param     abs_max    Maximum allowed parameter change
#' @param     dose_abs_max    Maximum allowed threshold parameter change
#' @param     df_groups    matrix with time and event information
#' @param     tu    event times
#' @param     verbose    verbosity boolean
#' @param     debugging    debugging boolean
#' @param     KeepConstant    vector identifying constant parameters
#' @param     term_tot    total number of terms
#' @param     ties_method    ties method
#'
#' @return List of results: scaled schoenfeld residuals
Schoenfeld_Cox_PH <- function(Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, abs_max, dose_abs_max, df_groups, tu, verbose, debugging, KeepConstant, term_tot, ties_method) {
    .Call(`_Colossus_Schoenfeld_Cox_PH`, Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, abs_max, dose_abs_max, df_groups, tu, verbose, debugging, KeepConstant, term_tot, ties_method)
}

#' Primary poisson regression function
#' \code{LogLik_Poisson} Performs the calls to calculation functions, Structures the poisson regression, With verbose option prints out time stamps and intermediate sums of terms and derivatives
#'
#' @param     PyrC    person-year matrix
#' @param     Term_n    Term numbers
#' @param     tform    subterm types
#' @param     a_n    starting values
#' @param     x_all    covariate matrix
#' @param     dfc    covariate column numbers
#' @param     fir    first term number
#' @param     der_iden    subterm number for derivative tests
#' @param     modelform    model string
#' @param     lr    learning rate for newton step toward 0 derivative
#' @param     maxiter    maximum number of iterations
#' @param     halfmax    maximum number of half steps
#' @param     epsilon    minimum acceptable maximum parameter change
#' @param     dbeta_cap    learning rate for newton step toward 0 log-likelihood
#' @param     abs_max    Maximum allowed parameter change
#' @param     dose_abs_max    Maximum allowed threshold parameter change
#' @param     deriv_epsilon    threshold for near-zero derivative
#' @param     double_step controls the step calculation, 0 for independent changes, 1 for solving b=Ax with complete matrices
#' @param     change_all    boolean if every parameter is being updated
#' @param     verbose    verbosity boolean
#' @param     debugging    debugging boolean
#' @param     KeepConstant    vector identifying constant parameters
#' @param     term_tot    total number of terms
#'
#' @return List of results: Log-likelihood of optimum, first derivative of log-likelihood, second derivative matrix, parameter list, standard deviation estimate, AIC, deviance, model information
LogLik_Poisson <- function(PyrC, Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, double_step, change_all, verbose, debugging, KeepConstant, term_tot) {
    .Call(`_Colossus_LogLik_Poisson`, PyrC, Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, double_step, change_all, verbose, debugging, KeepConstant, term_tot)
}

#' Primary poisson regression function with strata effect
#' \code{LogLik_Poisson_STRATA} Performs the calls to calculation functions, Structures the poisson regression, With verbose option prints out time stamps and intermediate sums of terms and derivatives, all with strata effects
#'
#' @param     PyrC    person-year matrix
#' @param     Term_n    Term numbers
#' @param     tform    subterm types
#' @param     a_n    starting values
#' @param     x_all    covariate matrix
#' @param     dfc    covariate column numbers
#' @param     fir    first term number
#' @param     der_iden    subterm number for derivative tests
#' @param     modelform    model string
#' @param     lr    learning rate for newton step toward 0 derivative
#' @param     maxiter    maximum number of iterations
#' @param     halfmax    maximum number of half steps
#' @param     epsilon    minimum acceptable maximum parameter change
#' @param     dbeta_cap    learning rate for newton step toward 0 log-likelihood
#' @param     abs_max    Maximum allowed parameter change
#' @param     dose_abs_max    Maximum allowed threshold parameter change
#' @param     deriv_epsilon    threshold for near-zero derivative
#' @param     double_step controls the step calculation, 0 for independent changes, 1 for solving b=Ax with complete matrices
#' @param     change_all    boolean if every parameter is being updated
#' @param     verbose    verbosity boolean
#' @param     debugging    debugging boolean
#' @param     KeepConstant    vector identifying constant parameters
#' @param     term_tot    total number of terms
#' @param     STRATA_vals vector of strata identifier values
#' @param     keep_strata boolean to return the strata parameter values
#'
#' @return List of results: Log-likelihood of optimum, first derivative of log-likelihood, second derivative matrix, parameter list, standard deviation estimate, AIC, deviance, model information
LogLik_Poisson_STRATA <- function(PyrC, Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, double_step, change_all, verbose, debugging, KeepConstant, term_tot, STRATA_vals, keep_strata) {
    .Call(`_Colossus_LogLik_Poisson_STRATA`, PyrC, Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, double_step, change_all, verbose, debugging, KeepConstant, term_tot, STRATA_vals, keep_strata)
}

#' Primary Cox PH stress test function
#' \code{Stress_Run} Performs the calls to calculation functions, Structures running one iteration of the cox PH regression, With verbose option prints out time stamps and intermediate sums of terms and derivatives, Prints out further timestamps within calculation calls
#'
#' @param     Term_n    Term numbers
#' @param     tform    subterm types
#' @param     a_n    starting values
#' @param     x_all    covariate matrix
#' @param     dfc    covariate column numbers
#' @param     fir    first term number
#' @param     der_iden    subterm number for derivative tests
#' @param     modelform    model string
#' @param     lr    learning rate for newton step toward 0 derivative
#' @param     maxiter    maximum number of iterations
#' @param     halfmax    maximum number of half steps
#' @param     epsilon    minimum acceptable maximum parameter change
#' @param     dbeta_cap    learning rate for newton step toward 0 log-likelihood
#' @param     abs_max    Maximum allowed parameter change
#' @param     dose_abs_max    Maximum allowed threshold parameter change
#' @param     deriv_epsilon    threshold for near-zero derivative
#' @param     df_groups    matrix with time and event information
#' @param     tu    event times
#' @param     double_step controls the step calculation, 0 for independent changes, 1 for solving b=Ax with complete matrices
#' @param     change_all    boolean if every parameter is being updated
#' @param     verbose    verbosity boolean
#' @param     debugging    debugging boolean
#' @param     KeepConstant    vector identifying constant parameters
#' @param     term_tot    total number of terms
#' @param     debug_checks    string vector of functions to test
#' @param     ties_method    ties method
#'
#' @return NULL
Stress_Run <- function(Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, df_groups, tu, double_step, change_all, verbose, debugging, KeepConstant, term_tot, debug_checks, ties_method) {
    invisible(.Call(`_Colossus_Stress_Run`, Term_n, tform, a_n, x_all, dfc, fir, der_iden, modelform, lr, maxiter, halfmax, epsilon, dbeta_cap, abs_max, dose_abs_max, deriv_epsilon, df_groups, tu, double_step, change_all, verbose, debugging, KeepConstant, term_tot, debug_checks, ties_method))
}

#' Primary Cox PH null model function
#' \code{LogLik_Cox_PH_null} Performs the calls to calculation functions, Structures the Cox PH null model, With verbose option prints out time stamps and intermediate sums of terms and derivatives
#'
#' @param     df_groups    status/time matrix
#' @param     tu    vector of event times
#' @param     verbose    verbose boolean
#' @param     ties_method    tied event method
#'
#' @return List of results: Log-likelihood of optimum, AIC
LogLik_Cox_PH_null <- function(df_groups, tu, verbose, ties_method) {
    .Call(`_Colossus_LogLik_Cox_PH_null`, df_groups, tu, verbose, ties_method)
}

#' Primary reference vector risk function
#' \code{RISK_SUBSET} Performs the calls to calculation functions, Calculates risk for a set of reference vectors, With verbose option prints out time stamps and intermediate sums of terms and derivatives
#'
#' @param     Term_n    Term numbers
#' @param     tform    subterm types
#' @param     a_n    starting values
#' @param     x_all    covariate matrix
#' @param     dfc    covariate column numbers
#' @param     fir    first term number
#' @param     modelform    model string
#' @param     verbose    verbosity boolean
#' @param     debugging    debugging boolean
#' @param     term_tot    total number of terms
#'
#' @return List of results: Risk at the reference
RISK_SUBSET <- function(Term_n, tform, a_n, x_all, dfc, fir, modelform, verbose, debugging, term_tot) {
    .Call(`_Colossus_RISK_SUBSET`, Term_n, tform, a_n, x_all, dfc, fir, modelform, verbose, debugging, term_tot)
}

#' Interface between R code and the Cox PH regression
#' \code{cox_ph_transition} Called directly from R, Defines the control variables and calls the regression function
#' @param Term_n Term numbers
#' @param tform subterm types
#' @param a_n starting values
#' @param dfc covariate column numbers
#' @param x_all covariate matrix
#' @param fir first term number
#' @param der_iden subterm number for derivative tests
#' @param modelform model string
#' @param Control control list
#' @param df_groups time and event matrix
#' @param tu event times
#' @param KeepConstant vector of parameters to keep constant
#' @param term_tot total number of terms
#'
#' @return LogLik_Cox_PH output : Log-likelihood of optimum, first derivative of log-likelihood, second derivative matrix, parameter list, standard deviation estimate, AIC, model information
cox_ph_transition <- function(Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, df_groups, tu, KeepConstant, term_tot) {
    .Call(`_Colossus_cox_ph_transition`, Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, df_groups, tu, KeepConstant, term_tot)
}

#' Interface between R code and the Cox PH regression for basic model
#' \code{cox_ph_transition_basic} Called directly from R, Defines the control variables and calls the regression function
#' @param a_n starting values
#' @param dfc covariate column numbers
#' @param x_all covariate matrix
#' @param der_iden subterm number for derivative tests
#' @param Control control list
#' @param df_groups time and event matrix
#' @param tu event times
#' @param KeepConstant vector of parameters to keep constant
#'
#' @return LogLik_Cox_PH output : Log-likelihood of optimum, first derivative of log-likelihood, second derivative matrix, parameter list, standard deviation estimate, AIC, model information
cox_ph_transition_basic <- function(a_n, dfc, x_all, der_iden, Control, df_groups, tu, KeepConstant) {
    .Call(`_Colossus_cox_ph_transition_basic`, a_n, dfc, x_all, der_iden, Control, df_groups, tu, KeepConstant)
}

#' Interface between R code and the Cox PH regression with STRATA
#' \code{cox_ph_STRATA} Called directly from R, Defines the control variables and calls the regression function
#' @param Term_n Term numbers
#' @param tform subterm types
#' @param a_n starting values
#' @param dfc covariate column numbers
#' @param x_all covariate matrix
#' @param fir first term number
#' @param der_iden subterm number for derivative tests
#' @param modelform model string
#' @param Control control list
#' @param df_groups time and event matrix
#' @param tu event times
#' @param KeepConstant vector of parameters to keep constant
#' @param term_tot total number of terms
#' @param STRATA_vals vector of strata identifier values
#'
#' @return LogLik_Cox_PH output : Log-likelihood of optimum, first derivative of log-likelihood, second derivative matrix, parameter list, standard deviation estimate, AIC, model information
cox_ph_STRATA <- function(Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, df_groups, tu, KeepConstant, term_tot, STRATA_vals) {
    .Call(`_Colossus_cox_ph_STRATA`, Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, df_groups, tu, KeepConstant, term_tot, STRATA_vals)
}

#' Interface between R code and the Cox PH plotting
#' \code{cox_ph_plot} Called directly from R, Defines the control variables and calls the correct plotting function
#' @param Term_n Term numbers
#' @param tform subterm types
#' @param a_n optimal values
#' @param a_er optimal value standard error
#' @param dfc covariate column numbers
#' @param x_all covariate matrix
#' @param fir first term number
#' @param der_iden subterm number for derivative tests
#' @param modelform model string
#' @param Control control list
#' @param df_groups time and event matrix
#' @param tu event times
#' @param KeepConstant vector of parameters to keep constant
#' @param term_tot total number of terms
#' @param Plot_Type string specifying which plot type
#' @param uniq_v total number of unique covariate values
#'
#' @return Cox_PH_PLOT_SURV : ( baseline harzard, risk for each row) or Cox_PH_PLOT_RISK output : (covariate values, risks for each row)
cox_ph_plot <- function(Term_n, tform, a_n, a_er, dfc, x_all, fir, der_iden, modelform, Control, df_groups, tu, KeepConstant, term_tot, Plot_Type, uniq_v) {
    .Call(`_Colossus_cox_ph_plot`, Term_n, tform, a_n, a_er, dfc, x_all, fir, der_iden, modelform, Control, df_groups, tu, KeepConstant, term_tot, Plot_Type, uniq_v)
}

#' Interface between R code and the schoenfeld residual calculation
#' \code{cox_ph_schoenfeld_transition} Called directly from R, Defines the control variables and calls the calculation function
#' @param Term_n Term numbers
#' @param tform subterm types
#' @param a_n starting values
#' @param dfc covariate column numbers
#' @param x_all covariate matrix
#' @param fir first term number
#' @param der_iden subterm number for derivative tests
#' @param modelform model string
#' @param Control control list
#' @param df_groups time and event matrix
#' @param tu event times
#' @param KeepConstant vector of parameters to keep constant
#' @param term_tot total number of terms
#'
#' @return Schoenfeld_Cox_PH output: scaled schoenfeld residuals
cox_ph_schoenfeld_transition <- function(Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, df_groups, tu, KeepConstant, term_tot) {
    .Call(`_Colossus_cox_ph_schoenfeld_transition`, Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, df_groups, tu, KeepConstant, term_tot)
}

#' Interface between R code and the poisson regression
#' \code{poisson_transition} Called directly from R, Defines the control variables and calls the regression function
#' @param dfe Matrix with person-year/event count information
#' @param Term_n Term numbers
#' @param tform subterm types
#' @param a_n starting values
#' @param dfc covariate column numbers
#' @param x_all covariate matrix
#' @param fir first term number
#' @param der_iden subterm number for derivative tests
#' @param modelform model string
#' @param Control control list
#' @param KeepConstant vector of parameters to keep constant
#' @param term_tot total number of terms
#'
#' @return LogLik_Poisson output : Log-likelihood of optimum, first derivative of log-likelihood, second derivative matrix, parameter list, standard deviation estimate, AIC, deviance, model information
poisson_transition <- function(dfe, Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, KeepConstant, term_tot) {
    .Call(`_Colossus_poisson_transition`, dfe, Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, KeepConstant, term_tot)
}

#' Interface between R code and the poisson regression with strata effect
#' \code{poisson_strata_transition} Called directly from R, Defines the control variables and calls the regression function with strata effect
#' @param dfe Matrix with person-year/event count information
#' @param Term_n Term numbers
#' @param tform subterm types
#' @param a_n starting values
#' @param dfc covariate column numbers
#' @param x_all covariate matrix
#' @param fir first term number
#' @param der_iden subterm number for derivative tests
#' @param modelform model string
#' @param Control control list
#' @param KeepConstant vector of parameters to keep constant
#' @param term_tot total number of terms
#' @param STRATA_vals vector of strata identifier values
#'
#' @return LogLik_Poisson output : Log-likelihood of optimum, first derivative of log-likelihood, second derivative matrix, parameter list, standard deviation estimate, AIC, deviance, model information
poisson_strata_transition <- function(dfe, Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, KeepConstant, term_tot, STRATA_vals) {
    .Call(`_Colossus_poisson_strata_transition`, dfe, Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, KeepConstant, term_tot, STRATA_vals)
}

#' Interface between R code and the Cox PH stress tester
#' \code{Stress_Test} Called directly from R, Defines the verbosity and tie method variables, Calls the calculation function
#' @param Term_n Term numbers
#' @param tform subterm types
#' @param a_n starting values
#' @param dfc covariate column numbers
#' @param x_all covariate matrix
#' @param fir first term number
#' @param der_iden subterm number for derivative tests
#' @param modelform model string
#' @param Control control list
#' @param df_groups time and event matrix
#' @param tu event times
#' @param KeepConstant vector of parameters to keep constant
#' @param term_tot total number of terms
#' @param test_point string vector of functions to test further
#'
#' @return NULL
Stress_Test <- function(Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, df_groups, tu, KeepConstant, term_tot, test_point) {
    invisible(.Call(`_Colossus_Stress_Test`, Term_n, tform, a_n, dfc, x_all, fir, der_iden, modelform, Control, df_groups, tu, KeepConstant, term_tot, test_point))
}

#' Interface between R code and the Cox PH null model function
#' \code{Stress_Test} Called directly from R, Defines the control variables and calls the calculation function
#' @param Control control list
#' @param df_groups time and event matrix
#' @param tu event times
#'
#' @return LogLike_Cox_PH_null output : Log-likelihood of optimum, AIC
cox_ph_null <- function(Control, df_groups, tu) {
    .Call(`_Colossus_cox_ph_null`, Control, df_groups, tu)
}

#' Interface between R code and the reference risk calculation
#' \code{cox_ph_risk_sub} Called directly from R, Defines the control variables and calls the calculation function
#' @param Term_n Term numbers
#' @param tform subterm types
#' @param a_n starting values
#' @param dfc covariate column numbers
#' @param x_all covariate matrix
#' @param fir first term number
#' @param modelform model string
#' @param Control control list
#' @param term_tot total number of terms
#'
#' @return RISK_SUBSET output: Risk at the reference
cox_ph_risk_sub <- function(Term_n, tform, a_n, dfc, x_all, fir, modelform, Control, term_tot) {
    .Call(`_Colossus_cox_ph_risk_sub`, Term_n, tform, a_n, dfc, x_all, fir, modelform, Control, term_tot)
}

#' Generates csv file with time-dependent columns
#' \code{Write_Time_Dep} Called directly from R, Defines a new matrix which interpolates time-dependent values on a grid
#' @param df0_Times Matrix with (starting time, ending time)
#' @param df0_dep matrix with pairs of (covariate at start, covariate at end) for each time-dependent covariate
#' @param df0_const matrix with values that are held constant
#' @param df0_event matrix with event status, zero up to the last entry for each original row
#' @param dt spacing in time
#' @param filename file to save the data to
#' @param tform vector with types of time dependent variables
#' @param tu list of event times
#' @param iscox boolean of cox formatting is used
#'
#' @return saves a dataframe to be used with time-dependent covariate analysis
Write_Time_Dep <- function(df0_Times, df0_dep, df0_const, df0_event, dt, filename, tform, tu, iscox) {
    invisible(.Call(`_Colossus_Write_Time_Dep`, df0_Times, df0_dep, df0_const, df0_event, dt, filename, tform, tu, iscox))
}

