on: [workflow_dispatch]

name: ARM and AMD check

permissions:
  contents: write

jobs:
  build:
    name: Check Colossus on ${{ matrix.arch }}
    runs-on: ubuntu-24.04${{matrix.arch=='arm64' && '-arm' || ''}}
    strategy:
      fail-fast: false
      matrix:
        arch: [ 'amd64', 'arm64' ]
    container:
      image: ghcr.io/r-devel/rcheckserver/ubuntu:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        R -q -e 'pak::pkg_install(c("deps::.", "any::rcmdcheck"), dependencies = TRUE)'
    - uses: r-lib/actions/check-r-package@v2
