# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: CUSTOM_LINTS

on:
  workflow_dispatch:
    branches: [main, dev]
  push:
    branches: [main, dev]

permissions: read-all

jobs:
  cpplint_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        pipx run cpplint --filter=-whitespace/line_length,-readability/fn_size,-runtime/references --exclude=src/RcppExports.* --exclude=src/*.*o --exclude=src/Makevars* src/*.* &> cpplint_out.txt
        if grep -q 'Total errors found:' cpplint_out.txt; then
            echo "cpplint error"
            exit 1
        fi
  lintr:
    name: Run lintr scanning
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, local::.
          needs: lint

      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
