# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: CUSTOM_LINTS

on:
  workflow_dispatch:
    branches: [main, dev]
  push:
    branches: [main, dev]

permissions: read-all

jobs:
  goodpractice_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: 2
      - name: install libraries
        run: |
          sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libuv1-dev
      - name: move to package and check
        run: |
          ls
          Rscript -e "install.packages(c('devtools', 'remotes', 'goodpractice', 'withr'))"
          Rscript -e "pak::local_install_deps(dependencies = TRUE)"
          Rscript -e "pak::local_install_dev_deps(dependencies = TRUE)"
          Rscript -e "devtools::install()"
      - name: run tests
        run: |
           Rscript -e "g <- withr::with_options(list(goodpractice.exclude_path = c('./R/RcppExports.R', './tests/testthat/'), goodpractice.function_length_limit = 1000),goodpractice::gp('.', checks = goodpractice::checks_by_group('revdep', 'code_structure', 'spelling', 'urlchecker', 'vignette', 'description', 'package_structure')))
           print(g)
           if (length(goodpractice::failed_checks(g)) != 0){
             stop('Failed checks')
           }
           "
  cpplint_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        pipx run cpplint --filter=-whitespace/line_length,-readability/fn_size,-runtime/references --exclude=src/RcppExports.* --exclude=src/*.*o --exclude=src/Makevars* src/*.* &> cpplint_out.txt
        if grep -q 'Total errors found:' cpplint_out.txt; then
            echo "cpplint error"
            exit 1
        fi
  lintr:
    name: Run lintr scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, local::.
          needs: lint

      - name: Lint
        run: lintr::sarif_output(lintr::lint_package(), "lintr-results.sarif")
        shell: Rscript {0}
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: lintr-results.sarif
          wait-for-processing: true
