# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: OS_Log_Check

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  mac_no_OMP_check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: 2
          remove-openmp-macos: false
      - name: move to package and install
        run: |
          ls
          Rscript -e "install.packages(c('devtools','bit64'))"
          Rscript -e "devtools::install_deps(dependencies = TRUE)"
          Rscript -e "devtools::install_dev_deps(dependencies = TRUE)"
          Rscript -e "devtools::install()"
      - name: Run the test
        run: |
           Rscript excess_test/Lin_Test.R
  win_check:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: 2
      - name: move to package and check
        run: |
          ls
          Rscript -e "install.packages(c('devtools','bit64'))"
          Rscript -e "devtools::install_deps(dependencies = TRUE)"
          Rscript -e "devtools::install_dev_deps(dependencies = TRUE)"
          Rscript -e "devtools::install()"
      - name: Run the test
        run: |
           Rscript excess_test/Lin_Test.R
  ubuntu_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: 2
      - name: install libraries
        run: |
          sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      - name: move to package and check
        run: |
          ls
          Rscript -e "install.packages(c('devtools','bit64'))"
          Rscript -e "devtools::install_deps(dependencies = TRUE)"
          Rscript -e "devtools::install_dev_deps(dependencies = TRUE)"
          Rscript -e "devtools::install()"
      - name: Run the test
        run: |
           Rscript excess_test/Lin_Test.R
