# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: OS_Checks

on: [push, workflow_dispatch]

permissions:
  contents: read

env:
	CC: clang

jobs:
  ubuntu_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Set up R
      - uses: r-lib/actions/setup-r@v2
        name: install libraries
        run: |
          sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      - name: move to package and install dependencies
        run: |
          Rscript -e "install.packages(c('devtools'))"
          Rscript -e "devtools::install_deps(dependencies = TRUE)"
          Rscript -e "devtools::install_dev_deps(dependencies = TRUE)"
	  - name: run installation
        run: |
          Rscript -e "devtools::install()"
