# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  mac_check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: enable homebrew to allow OpenMP
        run: |
          brew install llvm
          clang --version
          curl -O https://mac.r-project.org/openmp/openmp-14.0.6-darwin20-Release.tar.gz
          sudo tar fvxz openmp-14.0.6-darwin20-Release.tar.gz -C /
      - name: move to package and install
        run: |
          cd Colossus
          ls
          Rscript -e "install.packages(c('devtools'))"
          Rscript -e "devtools::install_deps(dependencies = TRUE)"
          Rscript -e "devtools::install_dev_deps(dependencies = TRUE)"
          Rscript -e "devtools::install()"
      - name: move to package and build examples
        run: |
          cd Colossus
          brew install pandoc
          Rscript -e "devtools::check(error_on = c('error'))"
      - name: move to package and run tests
        run: |
          cd Colossus
          Rscript -e "devtools::run_examples()"
          Rscript -e "devtools::test(stop_on_failure=TRUE)"
  win_check:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: move to package and check
        run: |
          cd Colossus
          ls
          Rscript -e "install.packages(c('devtools'))"
          Rscript -e "devtools::install_deps(dependencies = TRUE)"
          Rscript -e "devtools::install_dev_deps(dependencies = TRUE)"
          Rscript -e "devtools::install()"
      - name: move to package and build examples
        run: |
          choco install pandoc
          refreshenv
          cd Colossus
          Rscript -e "devtools::check(error_on = c('error'))"
      - name: move to package and run tests
        run: |
          cd Colossus
          Rscript -e "devtools::run_examples()"
          Rscript -e "devtools::test(stop_on_failure=TRUE)"
  ubuntu_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: install libraries
        run: |
          sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      - name: move to package and check
        run: |
          cd Colossus
          ls
          Rscript -e "install.packages(c('devtools'))"
          Rscript -e "devtools::install_deps(dependencies = TRUE)"
          Rscript -e "devtools::install_dev_deps(dependencies = TRUE)"
          Rscript -e "devtools::install()"
      - name: move to package and build examples
        run: |
          cd Colossus
          sudo apt-get install pandoc
          sudo apt-get install texlive
          Rscript -e "devtools::check(error_on = c('error'))"
      - name: move to package and run tests
        run: |
          cd Colossus
          Rscript -e "devtools::run_examples()"
          Rscript -e "devtools::test(stop_on_failure=TRUE)"
