# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on: workflow_dispatch

permissions:
  contents: read

jobs:
  mac_check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: enable homebrew to allow OpenMP
        run: |
          brew install llvm
          clang --version
          curl -O https://mac.r-project.org/openmp/openmp-14.0.6-darwin20-Release.tar.gz
          sudo tar fvxz openmp-14.0.6-darwin20-Release.tar.gz -C /
      - name: move to package and check
        run: |
          cd Colossus
          ls
          bash configure_MAKEVAR.sh
          Rscript -e "install.packages(c('devtools'))"
          Rscript -e "devtools::install_deps(dependencies = TRUE)"
          Rscript -e "devtools::install_dev_deps(dependencies = TRUE)"
          Rscript -e "devtools::load_all()"
          Rscript -e "devtools::install()"
          Rscript -e "devtools::test()"
  win_check:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: move to package and check
        run: |
          cd Colossus
          ls
          Rscript -e "install.packages(c('devtools'))"
          Rscript -e "devtools::install_deps(dependencies = TRUE)"
          Rscript -e "devtools::install_dev_deps(dependencies = TRUE)"
          Rscript -e "devtools::load_all()"
          Rscript -e "devtools::install()"
          Rscript -e "devtools::test()"
  ubuntu_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: install libraries
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      - name: move to package and check
        run: |
          cd Colossus
          ls
          bash configure_MAKEVAR.sh
          Rscript -e "install.packages(c('devtools'))"
          Rscript -e "devtools::install_deps(dependencies = TRUE)"
          Rscript -e "devtools::install_dev_deps(dependencies = TRUE)"
          Rscript -e "devtools::load_all()"
          Rscript -e "devtools::install()"
          Rscript -e "devtools::test()"
