# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Valgrind_Test

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ubuntu_valgrind_R_CMD_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: 2
      - name: Run R CMD check with valgrind
        run: |
          R CMD build ---no-build-vignettes --no-manual .
          R CMD check --use-valgrind --no-vignettes --no-manual *_*.tar.gz
  ubuntu_valgrind_R_D_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: 2
      - name: Run R CMD check with valgrind
        run: |
          printf "devtools::run_examples()\ndevtools::test()" > memcheck.R
          R -d "valgrind --tool=memcheck --leak-check=full" --vanilla < memcheck.R
